---
title: 异常
updated: 2020-12-09T20:35:05.0000000+08:00
created: 2020-08-31T09:39:57.0000000+08:00
---

# 异常
2020年8月31日
9:39

## 一，异常概述与异常体系结构
| Error     | Java虚拟机无法解决的严重问题。比如：StackOverflowError啊和OOM。一般不编写针对性 的代码进行处理。 |
|-----------|--------------------------------------------------------------------------------------------------|
| Exception | 其它因编程错误或偶然的外在因素导致的一般性问题，可以使 用针对性的代码进行处理。                  |
## 二、常见异常

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>java.lang.Throwable</p>
<p>|-----java.lang.Error:一般不编写针对性的代码进行处理。</p>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>//1.栈溢出：java.lang.StackOverflowError</p>
<p>main(args);</p>
<p>//2.堆溢出：java.lang.OutOfMemoryError</p>
<p>Integer[] arr = new Integer[1024*1024*1024];</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<p>|-----java.lang.Exception:可以进行异常的处理</p>
<p>|------编译时异常(checked)</p>
<p>|-----IOException</p>
<p>|-----FileNotFoundException</p>
<p>|-----ClassNotFoundException</p>
<p>|------运行时异常(unchecked,RuntimeException)</p>
<p>|-----NullPointerException</p>
<p>|-----ArrayIndexOutOfBoundsException</p>
<p>|-----ClassCastException</p>
<p>|-----NumberFormatException</p>
<p>|-----InputMismatchException</p>
<p>|-----ArithmeticException</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p><strong>import java.io.*;</strong></p>
<p><strong>public class ExceptionTest {</strong></p>
<p><strong></strong></p>
<p><strong>//******************以下是运行时异常***************************</strong></p>
<p><strong>//ArithmeticException</strong></p>
<p><strong>@Test</strong></p>
<p><strong>public void test6(){</strong></p>
<p><strong>int a = 10;</strong></p>
<p><strong>int b = 0;</strong></p>
<p><strong>System.out.println(a / b);</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>//InputMismatchException</strong></p>
<p><strong>@Test</strong></p>
<p><strong>public void test5(){</strong></p>
<p><strong>Scanner scanner = new Scanner(System.in);</strong></p>
<p><strong>int score = scanner.nextInt();</strong></p>
<p><strong>System.out.println(score);</strong></p>
<p><strong></strong></p>
<p><strong>scanner.close();</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>//NumberFormatException</strong></p>
<p><strong>@Test</strong></p>
<p><strong>public void test4(){</strong></p>
<p><strong></strong></p>
<p><strong>String str = "123";</strong></p>
<p><strong>str = "abc";</strong></p>
<p><strong>int num = Integer.parseInt(str);</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>//ClassCastException</strong></p>
<p><strong>@Test</strong></p>
<p><strong>public void test3(){</strong></p>
<p><strong>Object obj = new Date();</strong></p>
<p><strong>String str = (String)obj;</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>//IndexOutOfBoundsException</strong></p>
<p><strong>@Test</strong></p>
<p><strong>public void test2(){</strong></p>
<p><strong>//ArrayIndexOutOfBoundsException</strong></p>
<p><strong>//int[] arr = new int[10];</strong></p>
<p><strong>//System.out.println(arr[10]);</strong></p>
<p><strong>//StringIndexOutOfBoundsException</strong></p>
<p><strong>String str = "abc";</strong></p>
<p><strong>System.out.println(str.charAt(3));</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>//NullPointerException</strong></p>
<p><strong>@Test</strong></p>
<p><strong>public void test1(){</strong></p>
<p><strong></strong></p>
<p><strong>//int[] arr = null;</strong></p>
<p><strong>//System.out.println(arr[3]);</strong></p>
<p><strong></strong></p>
<p><strong>String str = "abc";</strong></p>
<p><strong>str = null;</strong></p>
<p><strong>System.out.println(str.charAt(0));</strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p>
<p></p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
解决方式：
过程一："抛"：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象。并将此对象抛出。一旦抛出对象以后，其后的代码就不再执行。
关于异常对象的产生：① 系统自动生成的异常对象
 ② 手动的生成一个异常对象，并抛出（throw）
过程二："抓"：可以理解为异常的处理方式：① try-catch-finally ② throws
## 三、异常处理机制1:try-catch-finally
1，
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>try{</p>
<p>//可能出现异常的代码</p>
<p></p>
<p>}catch(异常类型1 变量名1){</p>
<p>//处理异常的方式1</p>
<p>}catch(异常类型2 变量名2){</p>
<p>//处理异常的方式2</p>
<p>}</p>
<p>....</p>
<p>finally{</p>
<p>//定会执行的代码</p>
<p>}</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
说明：
1\. **finally一定被执行**
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>1.finally是可选的</p>
<p>2.finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中有return语句，catch中有 return语句等情况。</p>
<p>3.像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
2\. 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配
3\. 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构（在没有写finally的情况）。继续执行其后的代码
4\. catch中的异常类型如果没有子父类关系，则谁声明在上，谁声明在下无所谓。catch中的异常类型如果满足子父类关系，则要求**子类一定声明在父类的上面。否则，报错**
5\. 常用的异常对象处理的方式： **① String getMessage() ② printStackTrace()**
6\. 在try结构中声明的变量，再出了try结构以后，就不能再被调用
7\. try-catch-finally结构可以嵌套
8.方法重写的规则之一：
子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型
注意
体会1：使用try-catch-finally处理编译时异常，是得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
体会2：开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，我们说一定要考虑异常的处理。
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>public void test(){</p>
<p>try{</p>
<p>File file = new File("hello.txt");</p>
<p>FileInputStream fis = new FileInputStream(file);</p>
<p></p>
<p>int data = fis.read();</p>
<p>while(data != -1){</p>
<p>System.out.print((char)data);</p>
<p>data = fis.read();</p>
<p>}</p>
<p></p>
<p>fis.close();</p>
<p>}catch(FileNotFoundException e){</p>
<p>e.printStackTrace();</p>
<p>}catch(IOException e){</p>
<p>e.printStackTrace();</p>
<p>}</p>
<p>}</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

## 四、异常处理机制二：throws
1\. "throws + 异常类型"写在方法的声明处。指明此方法执行时，可能会抛出的异常类型。 一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！
2\. 体会：try-catch-finally:真正的将异常给处理掉了。throws的方式只是将异常抛给了方法的调用者。 并没有真正将异常处理掉。
3\. 开发中如何选择使用try-catch-finally 还是使用throws？
3.1 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理。

3.2 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws

的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p><strong>import java.io.*;</strong></p>
<p><strong>public class ExceptionTest2 {</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>public static void main(String[] args){</strong></p>
<p><strong>try{</strong></p>
<p><strong>method2();</strong></p>
<p><strong></strong></p>
<p><strong>}catch(IOException e){</strong></p>
<p><strong>e.printStackTrace();</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>//method3();</strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>public static void method3(){</strong></p>
<p><strong>try {</strong></p>
<p><strong>method2();</strong></p>
<p><strong>} catch (IOException e) {</strong></p>
<p><strong>e.printStackTrace();</strong></p>
<p><strong>}</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>public static void method2() throws IOException{</strong></p>
<p><strong>method1();</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>public static void method1() throws FileNotFoundException,IOException{</strong></p>
<p><strong>File file = new File("hello1.txt");</strong></p>
<p><strong>FileInputStream fis = new FileInputStream(file);</strong></p>
<p><strong></strong></p>
<p><strong>int data = fis.read();</strong></p>
<p><strong>while(data != -1){</strong></p>
<p><strong>System.out.print((char)data);</strong></p>
<p><strong>data = fis.read();</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>fis.close();</strong></p>
<p><strong></strong></p>
<p><strong>System.out.println("hahaha!");</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p>
<p></p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
五、手动抛出异常throw
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p><strong>public class StudentTest {</strong></p>
<p><strong></strong></p>
<p><strong>public static void main(String[] args) {</strong></p>
<p><strong>try {</strong></p>
<p><strong>Student s = new Student();</strong></p>
<p><strong>s.regist(-1001);</strong></p>
<p><strong>System.out.println(s);</strong></p>
<p><strong>} catch (Exception e) {</strong></p>
<p><strong>System.out.println(e.getMessage());</strong></p>
<p><strong>}</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p>
<p></p>
<p></p>
<p><strong>class Student{</strong></p>
<p><strong></strong></p>
<p><strong>private int id;</strong></p>
<p><strong></strong></p>
<p><strong>public void regist(int id) throws Exception {</strong></p>
<p><strong>if(id &gt; 0){</strong></p>
<p><strong>this.id = id;</strong></p>
<p><strong>}else{</strong></p>
<p><strong>//手动抛出异常对象</strong></p>
<p><strong>throw new MyException("不能输入负数");</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p>
<p></p>
<p><strong>@Override</strong></p>
<p><strong>public String toString() {</strong></p>
<p><strong>return "Student [id=" + id + "]";</strong></p>
<p><strong>}</strong></p>
<p><strong></strong></p>
<p><strong></strong></p>
<p><strong>}</strong></p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
六、用户自定义异常类
如何自定义异常类？
1\. 继承于现有的异常结构：RuntimeException 、Exception
2\. 提供全局常量：serialVersionUID
3\. 提供重载的构造器
<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>public class MyException extends Exception{</p>
<p></p>
<p>static final long serialVersionUID = -7034897193246939L;</p>
<p></p>
<p>public MyException(){</p>
<p></p>
<p>}</p>
<p></p>
<p>public MyException(String msg){</p>
<p>super(msg);</p>
<p>}</p>
<p>}</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>

<table>
<colgroup>
<col style="width: 100%" />
</colgroup>
<thead>
<tr class="header">
<th><p>package basic.day16.ever;</p>
<p>//编写应用程序EcmDef.java，接收命令行的两个参数，要求不能输入负数，计算两数相除。</p>
<p>//对数据类型不一致(NumberFormatException)、缺少命令行参数(ArrayIndexOutOfBoundsException、</p>
<p>//除0(ArithmeticException)及输入负数(EcDef 自定义的异常)进行异常处理。</p>
<p>//提示：</p>
<p>//(1)在主类(EcmDef)中定义异常方法(ecm)完成两数相除功能。</p>
<p>//(2)在main()方法中使用异常处理语句进行异常处理。</p>
<p>//(3)在程序中，自定义对应输入负数的异常类(EcDef)。</p>
<p>//(4)运行时接受参数 java EcmDef 20 10 //args[0]=“20” args[1]=“10”</p>
<p>//(5)Interger类的static方法parseInt(String s)将s转换成对应的int值。</p>
<p>// 如：int a=Interger.parseInt(“314”);//a=314;</p>
<p>public class EcmDef {</p>
<p>public static void main(String[] args) {</p>
<p>try {</p>
<p>int i=Integer.parseInt(args[0]);</p>
<p>int j=Integer.parseInt(args[1]);</p>
<p>int result=ecm(i,j);</p>
<p>System.out.println(result);</p>
<p>}catch (NumberFormatException e) {</p>
<p>System.out.println("数据类型不一致");</p>
<p>}catch (ArrayIndexOutOfBoundsException e) {</p>
<p>System.out.println("缺少命令行参数");</p>
<p>}catch (ArithmeticException e) {</p>
<p>System.out.println("除0");</p>
<p>}catch (EcDef e) {</p>
<p>System.out.println(e.getMessage());</p>
<p>}</p>
<p></p>
<p></p>
<p>}</p>
<p>public static int ecm(int a,int b) throws EcDef{</p>
<p>if(a&gt;0&amp;&amp;b&gt;0) {</p>
<p>return a/b;</p>
<p>}else {</p>
<p>throw new EcDef ("不能输入负数");</p>
<p>}</p>
<p>}</p>
<p>}</p>
<p>class EcDef extends Exception{</p>
<p>static final long serialVersionUID=-33092390132l;</p>
<p>public EcDef() {</p>
<p></p>
<p>}</p>
<p>public EcDef(String msg) {</p>
<p>super(msg);</p>
<p>}</p>
<p>}</p></th>
</tr>
</thead>
<tbody>
</tbody>
</table>
